M48
; DRILL file {KiCad 9.0.7} date 2026-03-14T20:32:55+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-14T20:32:55+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.100
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.300
%
G90
G05
T1
X149.0Y-78.69
X149.0Y-86.31
T2
X133.42Y-79.0
X143.58Y-79.0
T3
X122.5Y-79.5
X122.5Y-84.5
X159.327Y-79.5
X159.327Y-84.5
M30
